name = "st_step"
main = "src/index.js"
compatibility_date = "2024-12-01"

assets = { directory = "public", binding = "ASSETS" }

[[durable_objects.bindings]]
name = "MY_DO"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyDurableObject"]
